import type {Metadata} from "next";
import {LegalShell} from "@/components/legal/legal-shell";
import {Navbar} from "@/components/navbar/nav";
import {auth} from "@/utils/auth";

export const metadata: Metadata = {
  title: "Terms of Service — DocuMind",
  description:
    "The terms that govern your use of the DocuMind study-guide platform.",
};

export default async function TermsPage() {
  const user = await auth();
  return (
    <>
      <Navbar user={user} />
      <LegalShell title="Terms of Service" lastUpdated="July 2, 2026">
      <section>
        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and
          use of DocuMind (&ldquo;the Service&rdquo;). By signing in or using the
          Service, you agree to these Terms. If you do not agree, please do not
          use the Service.
        </p>
      </section>

      <section>
        <h2>1. The Service</h2>
        <p>
          DocuMind turns your documents into study material, including summaries,
          flashcards, quizzes, mind maps, semantic search, and chat over your
          uploaded content. The Service is intended for learning and study
          purposes.
        </p>
      </section>

      <section>
        <h2>2. Eligibility &amp; Accounts</h2>
        <p>
          DocuMind is a study tool intended for learners of all ages. If you are
          a minor, you should use the Service with the involvement of a parent,
          guardian, or teacher. You access the Service through Google sign-in and
          are responsible for maintaining the security of your account and for all
          activity that occurs under it.
        </p>
      </section>

      <section>
        <h2>3. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>
            Upload content you do not have the right to use, or that is unlawful,
            infringing, or harmful.
          </li>
          <li>
            Attempt to disrupt, overload, reverse-engineer, or gain unauthorized
            access to the Service or its infrastructure.
          </li>
          <li>
            Misuse the AI features to generate abusive, infringing, or otherwise
            prohibited content.
          </li>
          <li>Resell or commercially exploit the Service without permission.</li>
        </ul>
      </section>

      <section>
        <h2>4. AI-Generated Content</h2>
        <p>
          Summaries, flashcards, quizzes, mind maps, and chat answers are
          generated by automated AI systems. They are provided for study purposes
          only, may contain errors or inaccuracies, and are not a substitute for
          the original source material or professional advice. You are
          responsible for verifying important information.
        </p>
      </section>

      <section>
        <h2>5. Your Content</h2>
        <p>
          You retain ownership of the documents and content you upload. You grant
          us permission to process this content as needed to operate the Service
          and generate study material, as described in our{" "}
          <a href="/privacy">Privacy Policy</a>.
        </p>
      </section>

      <section>
        <h2>6. Intellectual Property</h2>
        <p>
          The Service, including its software, design, and branding, is owned by
          DocuMind and protected by applicable laws. These Terms do not grant you
          any right to our trademarks or proprietary materials.
        </p>
      </section>

      <section>
        <h2>7. Third-Party Services</h2>
        <p>
          The Service relies on third-party providers (including Google,
          UploadThing, and OpenAI). Your use of the Service may also be subject to
          their terms, and we are not responsible for third-party services outside
          our control.
        </p>
      </section>

      <section>
        <h2>8. Disclaimers</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; without warranties of any kind, whether express or
          implied. We do not warrant that the Service will be uninterrupted,
          error-free, or that AI output will be accurate.
        </p>
      </section>

      <section>
        <h2>9. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, DocuMind shall not be liable for
          any indirect, incidental, or consequential damages arising from your use
          of, or inability to use, the Service.
        </p>
      </section>

      <section>
        <h2>10. Termination</h2>
        <p>
          You may stop using the Service at any time. We may suspend or terminate
          access if you violate these Terms or misuse the Service.
        </p>
      </section>

      <section>
        <h2>11. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Material changes will be
          reflected by updating the &ldquo;Last updated&rdquo; date at the top of
          this page. Continued use of the Service after changes take effect
          constitutes acceptance.
        </p>
      </section>

      <section>
        <h2>12. Contact</h2>
        <p>
          Questions about these Terms? You can reach the founder of DocuMind
          directly at{" "}
          <a href="mailto:mrityunjaytiwari1873@gmail.com">
            mrityunjaytiwari1873@gmail.com
          </a>
          . Every message is read and answered personally.
        </p>
      </section>
      </LegalShell>
    </>
  );
}
