"use client"

import { Download } from "lucide-react"
import { Button } from "../ui/button"
import {jsPDF} from 'jspdf' 
// import '../fonts/NotoEmoji-Regular-normal.js'
import '../fonts/NotoEmoji-Regular-normal'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

interface downloadButtonProps {
    title: string, 
    summary_text: string, 
    file_name: string,
    created_at: Date
}
export default function DownloadSummaryButton({title, summary_text, file_name, created_at}: downloadButtonProps) {
    const handleDownload = async () => {
        const summaryContent = `Title - ${title}
        Generated summary
        generated on : ${new Date(created_at).toLocaleDateString()}
        
        ${summary_text}
        
        Original Filename: ${file_name}
        Generated by SummariZE`

        const blob = new Blob([summaryContent], {type: 'text/plain'})
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary - ${title}.txt`
        link.click();

        document.body.removeChild(link);
        URL.revokeObjectURL(url)


        // TRYING TO DOWNLOAD A PDF FILE INSTEAD OF NORMAL TEXT FILE WITH EMOJI
        // const doc = new jsPDF();

        // doc.setFont('NotoEmoji', 'normal')
        // doc.text(`Title 🙏🙏 - ${title}`, 10, 10);
        // doc.text(`Generated on : ${new Date(created_at).toLocaleDateString()}`, 10, 30)
        // doc.text(summary_text, 10, 40)
        // doc.text(`Original filename - ${file_name}`, 10, 60)
        // doc.text(`Generated by summarize`, 10, 70)
        // doc.save(`Summary- ${title}.pdf`)
        
        
        
    }
    return (
        <Button size={'sm'} className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50 hover:sclae-105 transition-all duration-300" onClick={handleDownload}>
            <Download className="h-4 w-4 mr-1" /> Download Summary
        </Button>
    )
}