"use client"

import { Download } from "lucide-react"
import { Button } from "../ui/button"

interface downloadButtonProps {
    title: string, 
    summary_text: string, 
    file_name: string,
    created_at: Date
}

export default function DownloadSummaryButton({title, summary_text, file_name, created_at}: downloadButtonProps) {
    const handleDownload = async () => {
        const summaryContent = `Title - ${title}
        Generated summary
        generated on : ${new Date(created_at).toLocaleDateString()}
        
        ${summary_text}
        
        Original Filename: ${file_name}
        Generated by SummariZE`

        const blob = new Blob([summaryContent], {type: 'text/plain'})
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary - ${title}.txt`
        link.click();

        document.body.removeChild(link);
        URL.revokeObjectURL(url)
    }
    return (
        <Button size={'sm'} className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50 hover:sclae-105 transition-all duration-300" onClick={handleDownload}>
            <Download className="h-4 w-4 mr-1" /> Download Summary
        </Button>
    )
}